[[drone]]
id = 1
connected_node_ids = [2,3]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1,4]
pdr = 0.03

[[client]]
id = 3
connected_drone_ids = [1]

[[server]]
id = 4
connected_drone_ids = [2]